In [9]:
import numpy as np
import pandas as pd 
import seaborn as sns

In [10]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\maddi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [11]:
df = sns.load_dataset("diamonds")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [12]:
## cheking null values
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [13]:
## separating the data set x and y
y = df['price']
x = df.drop('price',axis=1)

In [14]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
dtypes: category(3), float64(6)
memory usage: 2.6 MB

In [15]:
x_num = x.select_dtypes(include ="float64")
x_num.head()

   carat  depth  table     x     y     z
0   0.23   61.5   55.0  3.95  3.98  2.43
1   0.21   59.8   61.0  3.89  3.84  2.31
2   0.23   56.9   65.0  4.05  4.07  2.31
3   0.29   62.4   58.0  4.20  4.23  2.63
4   0.31   63.3   58.0  4.34  4.35  2.75

In [16]:
x_char = x.select_dtypes(exclude="float64")
x_char.head()

       cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [18]:
for col in x_char:
    x_char[col] = le.fit_transform(x_char[col])
x_char.head()

   cut  color  clarity
0    2      1        3
1    3      1        2
2    1      1        4
3    3      5        5
4    1      6        3

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [20]:
x_scaling = pd.DataFrame(sc.fit_transform(x_char),
                         columns = x_char.columns,
                         index=x_char.index)
x_scaling.head()

        cut     color   clarity
0 -0.538099 -0.937163 -0.484264
1  0.434949 -0.937163 -1.064117
2 -1.511147 -0.937163  0.095589
3  0.434949  1.414272  0.675442
4 -1.511147  2.002131 -0.484264

In [21]:
data = pd.concat([x_char,x_scaling],axis=1)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    data,y, test_size=0.2,random_state=45)

In [23]:
x_train.head()

       cut  color  clarity       cut     color   clarity
30833    3      4        4  0.434949  0.826413  0.095589
9693     2      5        6 -0.538099  1.414272  1.255295
38877    3      0        5  0.434949 -1.525021  0.675442
47811    2      3        7 -0.538099  0.238555  1.835148
29452    1      1        6 -1.511147 -0.937163  1.255295

In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((43152, 6), (10788, 6), (43152,), (10788,))

In [25]:
from sklearn.neighbors import KNeighborsRegressor
neigh = 10
knn = KNeighborsRegressor(n_neighbors=neigh)

In [26]:
knn.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=10)

In [27]:
ypred = knn.predict(x_test)

In [28]:
## regression metrics
## mae,mse,rmse,r2
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [29]:
mae = mean_absolute_error(y_test,ypred)
print(mae)
mse = mean_squared_error(y_test,ypred)
print(mse)
rmse =root_mean_squared_error(y_test,ypred)
print(rmse)
r2 = r2_score(y_test,ypred)
r2

3012.399286243975
16585853.894791435
4072.573375003996

-0.03174553411289094

In [1]:
!pip install mlflow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlflow in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.16.1)
Requirement already satisfied: mlflow-skinny==3.16.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.16.1)
Requirement already satisfied: mlflow-tracing==3.16.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.16.1)
Requirement already satisfied: Flask-CORS<7 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.14.4)
Requirement already satisfied: alembic!=1.10.0,<2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (1.20.0)
Requirement already satisfied: cryptography<51,>=43.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (50.0.2)
Requirement already satisfied: docker<8,>=4.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<4,>=2.5.4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.4.0)
Requirement already satisfied: matplotlib<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.11.2)
Requirement already satisfied: numpy<3 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (2.5.3)
Requirement already satisfied: pandas<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.0.6)
Requirement already satisfied: pyarrow<26,>=4.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (25.0.1)
Requirement already satisfied: scikit-learn<2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (1.9.1)
Requirement already satisfied: scipy<2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (1.18.1)
Requirement already satisfied: skops<1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (0.16.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (2.1.3)
Requirement already satisfied: waitress<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: anyio!=4.15.0,<5,>=3.6.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (4.15.1)
Requirement already satisfied: cachetools<8,>=5.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (7.2.1)
Requirement already satisfied: click<9,>=7.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (8.5.0)
Requirement already satisfied: cloudpickle<4 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (0.147.0)
Requirement already satisfied: fastapi<1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (0.142.2)
Requirement already satisfied: gitpython<4,>=3.1.9 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (3.2.0)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (9.0.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (1.45.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (1.45.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (1.45.0)
Requirement already satisfied: packaging<27 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (2.13.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (1.2.4)
Requirement already satisfied: pyyaml<7,>=5.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (2.34.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (0.6.0)
Requirement already satisfied: starlette<2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (1.7.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mlflow-skinny==3.16.1->mlflow) (0.54.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.25.1)
Requirement already satisfied: Mako in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from alembic!=1.10.0,<2->mlflow) (1.4.3)
Requirement already satisfied: idna>=2.8 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from anyio!=4.15.0,<5,>=3.6.2->mlflow-skinny==3.16.1->mlflow) (3.20)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cryptography<51,>=43.0.0->mlflow) (2.1.1)
Requirement already satisfied: google-auth~=2.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow) (2.60.0)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow) (2.8.0)
Requirement already satisfied: pywin32>=304 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from docker<8,>=4.0.0->mlflow) (312)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fastapi<1->mlflow-skinny==3.16.1->mlflow) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fastapi<1->mlflow-skinny==3.16.1->mlflow) (0.0.5)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from Flask<4->mlflow) (3.0.4)
Requirement already satisfied: werkzeug>=3.1.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from Flask<4->mlflow) (3.1.9)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.16.1->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.16.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.16.1->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from graphene<4->mlflow) (3.2.13)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.16.1->mlflow) (4.1.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (1.5.1)
Requirement already satisfied: pillow>=9 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib<4->mlflow) (3.3.3)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.16.1->mlflow) (0.66b0)
Requirement already satisfied: tzdata in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas<4->mlflow) (2026.5)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.1->mlflow) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.16.1->mlflow) (2.46.5)
Requirement already satisfied: six>=1.5 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.1->mlflow) (3.5.2)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.16.1->mlflow) (2026.7.22)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn<2->mlflow) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn<2->mlflow) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn<2->mlflow) (3.7.0)
Requirement already satisfied: prettytable>=3.9 in C:\Users\maddi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from skops<1->mlflow) (3.18.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\maddi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import mlflow 
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

In [4]:
mlflow.set_experiment("diamond1_exp")

2026/10/06 13:56:38 INFO mlflow.tracking.fluent: Experiment with name 'diamond1_exp' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/2', creation_time=1791275198744, effective_trace_archival_retention=None, experiment_id='2', last_update_time=1791275198744, lifecycle_stage='active', name='diamond1_exp', tags={}, trace_location=None, workspace='default'>

In [6]:
mlflow.log_param("test_size",0.2)
mlflow.log_param("random_state",45)
mlflow.log_param("kneighbours",neigh)

10

In [30]:
mlflow.log_metric("mae",mae)
mlflow.log_metric("mse",mse)
mlflow.log_metric("rmse",rmse)
mlflow.log_metric("r2",r2)

In [32]:
mlflow.sklearn.log_model(sk_model=knn,
                         name="mymodel",skops_trusted_types=["sklearn.neighbors._kd_tree.KDTree",
                                                             "sklearn.metrics._dist_metrics.EuclideanDistance64"])

In [48]:
mlflow.sklearn.log_model(sk_model=knn,
                         name="mymodel",skops_trusted_types=["sklearn.neighbors._kd_tree.KDTree",
                                                             "sklearn.metrics._dist_metrics.EuclideanDistance64"],
                                                             registered_model_name="KNNMODEL")

Registered model 'KNNMODEL' already exists. Creating a new version of this model...
2026/10/06 14:40:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: KNNMODEL, version 3
Created version '3' of model 'KNNMODEL'.

In [49]:
my_model= mlflow.pyfunc.load_model(model_uri="models:/KNNMODEL/latest")

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [50]:
my_model.predict(x_test)

array([2694.6, 1779.5, 3463.6, ..., 4763.7, 1546.8, 3105.1],
      shape=(10788,))